#!/bin/sh

filenameMapping="s/TWikiApp/WikiApp/g;s/TWikiTopic/WikiTopic/g;s/TWikiForm/DataForm/g;s/TWikiWork/WikiWork/g;"
contentMapping="$filenameMapping;s/TWikiGuest/WikiGuest/g;s/TWikiContributor/ProjectContributor/g;s/TWiki\ topic/wiki\ topic/g;s/TWIKIWEB/SYSTEMWEB/g;s/TWiki\ name/wiki\ name/g;s/TWikiAdminGroup/AdminGroup/g;s/TWikiPreferences/DefaultPreferences/g;s/TWikiAccessControl/AccessControl/g;s/TWiki:Plugins/Foswiki:Extensions/g;s/TWikiDocumentation/CompleteDocumentation/g;s/TWikiRegistration/UserRegistration/g;s/twikiAlert/foswikiAlert/g;s/twikiFirstCol/foswikiFirstCol/g;s/twikiInputField/foswikiInputField/g;s/twikiForm/foswikiForm/g"

for file in `find -L -name '*TWiki*'|grep -v svn|grep -v changes|grep -v Trash|grep -v TestCases`; do 
  dir=`dirname $file`
  topic=`basename $file`
  newtopic=`echo $topic|sed "$filenameMapping"`
  if [ "$topic" != "$newtopic" ]; then
    mv -v $file $dir/$newtopic
  fi
done

find -L -type f -name '*txt' -not -regex '*.svn.*' \
  -exec sed -i "$contentMapping" {} \;
